version: '3.1'

services:
  auth-service:
    image: gradle:4.6-jdk9
    command: gradle bootRun
    ports:
      - "8080:8080"
    volumes:
      - ./auth:/home/gradle

  microservice:
    image: gradle:4.6-jdk9
    command: gradle bootRun
    ports:
      - "8081:8081"
    volumes:
      - ./microservice:/home/gradle